const actionTypes = {

	FETCH_ALL_COMMENT: 'FETCH_ALL_COMMENT',
	FETCH_ALL_COMMENT_SUCCESS: 'FETCH_ALL_COMMENT_SUCCESS',
	FETCH_ALL_COMMENT_FAILURE: 'FETCH_ALL_COMMENT_FAILURE',

	REPLY_COMMENT: 'REPLY_COMMENT',
	REPLY_COMMENT_SUCCESS: 'REPLY_COMMENT_SUCCESS',
	REPLY_COMMENT_FAILURE: 'REPLY_COMMENT_FAILURE',

	DELETE_COMMENT: 'DELETE_COMMENT',
	DELETE_COMMENT_SUCCESS: 'DELETE_COMMENT_SUCCESS',
	DELETE_COMMENT_FAILURE: 'DELETE_COMMENT_FAILURE',

	SIGN_UP: 'SIGN_UP',
	SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS',
	SIGN_UP_FAILURE: 'SIGN_UP_FAILURE',

	LOGIN: 'LOGIN',
	LOGIN_SUCCESS: 'LOGIN_SUCCESS',
	LOGIN_FAILURE: 'LOGIN_FAILURE',



};

export default actionTypes;