const actionTypes = {

	FETCH_ALL_COMMENT: 'FETCH_ALL_COMMENT',
	FETCH_ALL_COMMENT_SUCCESS: 'FETCH_ALL_COMMENT_SUCCESS',
	FETCH_ALL_COMMENT_FAILURE: 'FETCH_ALL_COMMENT_FAILURE',

	REPLY_COMMENT: 'REPLY_COMMENT',
	REPLY_COMMENT_SUCCESS: 'REPLY_COMMENT_SUCCESS',
	REPLY_COMMENT_FAILURE: 'REPLY_COMMENT_FAILURE',
	
	FETCH_COMMENT_REPLY: 'FETCH_COMMENT_REPLY',
	FETCH_COMMENT_REPLY_SUCCESS: 'FETCH_COMMENT_REPLY_SUCCESS',
	FETCH_COMMENT_REPLY_FAILURE: 'FETCH_COMMENT_REPLY_FAILURE',

	ADD_COMMENT: 'ADD_COMMENT',
	ADD_COMMENT_SUCCESS: 'ADD_COMMENT_SUCCESS',
	ADD_COMMENT_FAILURE: 'ADD_COMMENT_FAILURE',

	DELETE_COMMENT: 'DELETE_COMMENT',
	DELETE_COMMENT_SUCCESS: 'DELETE_COMMENT_SUCCESS',
	DELETE_COMMENT_FAILURE: 'DELETE_COMMENT_FAILURE',

	ADD_COMMENT_REPLY:  'ADD_COMMENT_REPLY',
	ADD_COMMENT_REPLY_FAILURE: 'ADD_COMMENT_REPLY_FAILURE',
	ADD_COMMENT_REPLY_SUCCESS: 'ADD_COMMENT_REPLY_SUCCESS',
	
	UPDATE_COMMENT:  'UPDATE_COMMENT',
	UPDATE_COMMENT_FAILURE: 'UPDATE_COMMENT_FAILURE',
	UPDATE_COMMENT_SUCCESS:'UPDATE_COMMENT_SUCCESS'





};

export default actionTypes;